### ISSUE TITLE
OpenSim-core Python Dockerfile ERROR in RUN opensim_build (Makefile:140: recipe for target 'all' failed)

### ISSUE THREAD

**Issue by pwesberg** [opensim-org/opensim-containers#4]
Dear OpenSim developers, Dear Ayman Habib,

I'm very happy you provide a dockerfile for OpenSim-Core with python bindings! We would like to integrate a docker container for our tests in the gitlab CI/CD pipeline for our research.

I tried to build a docker image using your script: 
https://github.com/opensim-org/opensim-containers/blob/master/opensim-core/opensim-python/dockerfile-ubuntu 

Unfortunately, on MacOS there is an error in the build process. (see message below). I tried some adjustments, such as setting the right timezone, or setting `FROM stanfordnmbl/opensim-deps:latest`, but the same error occurs. Do you have any idea, what causes the error and how to fix it?

I also tried your image from hub.docker `docker pull stanfordnmbl/opensim-python:latest`, which is working fine for me. For our application, we need to add some python packages, thats why I would like to build the image myself. 

```
> Executing task: docker build --pull --rm -f "Dockerfile" -t osimdocker:latest "." <

[+] Building 0.1s (2/3)                                                                                       
[+] Building 0.6s (2/3)                                                                                       
[+] Building 359.2s (8/8) FINISHED                                                                            
 => [internal] load build definition from Dockerfile                                                     0.0s
 => => transferring dockerfile: 37B                                                                      0.0s
 => [internal] load .dockerignore                                                                        0.0s
 => => transferring context: 2B                                                                          0.0s
 => [internal] load metadata for docker.io/aymanhab/opensim-deps:4.3.0                                   0.6s
 => [1/5] FROM docker.io/aymanhab/opensim-deps:4.3.0@sha256:8928164b7426a1cba1cf366eb1795b4a5d857c94afc  0.0s
 => CACHED [2/5] RUN ln -snf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && echo America/Los  0.0s
 => [3/5] RUN apt-get update && DEBIAN_FRONTEND=noninteractive && apt-get --yes install         python  67.4s
 => [4/5] RUN mkdir ~/swig-source && cd ~/swig-source         && wget https://github.com/swig/swig/arc  47.9s
 => ERROR [5/5] RUN mkdir opensim_build && cd opensim_build && cmake ../opensim-core       -DSWIG_DIR  243.2s 
------                                                                                                        
 > [5/5] RUN mkdir opensim_build && cd opensim_build && cmake ../opensim-core       -DSWIG_DIR=~/swig/share/swig -DSWIG_EXECUTABLE=~/swig/bin/swig -DBUILD_PYTHON_WRAPPING=ON       -DCMAKE_INSTALL_PREFIX="~/opensim_install" -DOPENSIM_DEPENDENCIES_DIR="~/opensim_dependencies_install"       -DOPENSIM_C3D_PARSER=ezc3d -DBUILD_TESTING=OFF       && make -j8 && make -j8 install && rm -rf ../opensim_build:                                       
#8 0.314 -- The C compiler identification is GNU 7.5.0                                                        
#8 0.381 -- The CXX compiler identification is GNU 7.5.0
#8 0.392 -- Check for working C compiler: /usr/bin/cc
#8 0.466 -- Check for working C compiler: /usr/bin/cc -- works
#8 0.467 -- Detecting C compiler ABI info
#8 0.547 -- Detecting C compiler ABI info - done
#8 0.559 -- Detecting C compile features
#8 0.793 -- Detecting C compile features - done
#8 0.799 -- Check for working CXX compiler: /usr/bin/c++
#8 0.880 -- Check for working CXX compiler: /usr/bin/c++ -- works
#8 0.881 -- Detecting CXX compiler ABI info
#8 0.967 -- Detecting CXX compiler ABI info - done
#8 0.977 -- Detecting CXX compile features
#8 1.346 -- Detecting CXX compile features - done
#8 1.347 -- NOTICE: Make sure all OpenSim dependencies are built with the same CMAKE_BUILD_TYPE (Linux) or CONFIGURATION (Xcode/MSVC) as OpenSim to avoid mysterious runtime errors.
#8 1.361 -- Found Git: /usr/bin/git (found version "2.17.1") 
#8 1.365 fatal: not a git repository (or any of the parent directories): .git
#8 1.367 fatal: not a git repository (or any of the parent directories): .git
#8 1.405 -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
#8 1.631 -- Found NumPy: /usr/lib/python3/dist-packages/numpy/core/include (found version "1.13.3") 
#8 1.640 -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3") 
#8 1.644 -- Attempting to use dependencies from /root/opensim_dependencies_install
#8 1.656 -- Looking for pthread.h
#8 1.731 -- Looking for pthread.h - found
#8 1.733 -- Looking for pthread_create
#8 1.812 -- Looking for pthread_create - not found
#8 1.813 -- Looking for pthread_create in pthreads
#8 1.876 -- Looking for pthread_create in pthreads - not found
#8 1.876 -- Looking for pthread_create in pthread
#8 1.954 -- Looking for pthread_create in pthread - found
#8 1.956 -- Found Threads: TRUE  
#8 1.983 -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
#8 1.990 -- Found ADOLC: /root/opensim_dependencies_install/adol-c/include  
#8 1.991 -- Checking for module 'ipopt'
#8 2.004 --   Found ipopt, version 3.12.8
#8 2.047 -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
#8 2.172 -- Found SWIG: /root/swig/bin/swig (found suitable version "4.0.2", minimum required is "4.0.0") 
#8 2.175 -- Discovering dependencies for SWIG module simbody (Python).
#8 2.462 -- Discovering dependencies for SWIG module common (Python).
#8 3.001 -- Discovering dependencies for SWIG module simulation (Python).
#8 3.675 -- Discovering dependencies for SWIG module actuators (Python).
#8 4.319 -- Discovering dependencies for SWIG module analyses (Python).
#8 5.101 -- Discovering dependencies for SWIG module tools (Python).
#8 5.792 -- Discovering dependencies for SWIG module examplecomponents (Python).
#8 6.441 -- Discovering dependencies for SWIG module moco (Python).
#8 7.158 -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
#8 7.163 -- Could NOT find LATEX (missing: LATEX_COMPILER PDFLATEX) 
#8 7.169 -- The following features have been enabled:
#8 7.169 
#8 7.169  * WITH_CASADI, Build CasADi support for Moco (OPENSIM_WITH_CASADI)
#8 7.169  * WITH_TROPTER, Build the tropter optimal control library (OPENSIM_WITH_TROPTER)
#8 7.169 
#8 7.169 -- The following OPTIONAL packages have been found:
#8 7.169 
#8 7.169  * Git
#8 7.169  * Simbody (required version >= 3.7)
#8 7.169  * docopt (required version >= 0.6.1)
#8 7.169 
#8 7.169 -- The following REQUIRED packages have been found:
#8 7.169 
#8 7.169  * PythonInterp (required version >= 3)
#8 7.169  * NumPy
#8 7.169  * PythonLibs (required version >= 3)
#8 7.169  * ezc3d
#8 7.169  * Threads
#8 7.169  * spdlog
#8 7.169  * casadi (required version >= 3.4.4), <https://web.casadi.org>
#8 7.169    Differentiation and optimizer interface.
#8 7.169  * Eigen3 (required version >= 3.3.1), <https://eigen.tuxfamily.org>
#8 7.169    Matrix library
#8 7.169  * PkgConfig
#8 7.169  * ColPack (required version >= 1.0.10), <https://github.com/CSCsw/ColPack>
#8 7.169    Exploiting sparsity structure of Jacobian
#8 7.169  * ADOLC, <https://projects.coin-or.org/ADOL-C>
#8 7.169    Computing derivatives for optimization
#8 7.169  * SWIG (required version >= 4.0.0)
#8 7.169 
#8 7.169 -- The following features have been disabled:
#8 7.169 
#8 7.169  * OpenMP, Parallelize derivative calculations (TROPTER_WITH_OPENMP)
#8 7.169  * WITH_SNOPT, Support the SNOPT optimization library (TROPTER_WITH_SNOPT)
#8 7.169 
#8 7.169 -- The following OPTIONAL packages have not been found:
#8 7.169 
#8 7.169  * Doxygen, <http://www.doxygen.org>
#8 7.169    Generate C++ API documentation
#8 7.169  * LATEX
#8 7.169 
#8 7.188 -- Configuring done
#8 7.487 -- Generating done
#8 7.500 -- Build files have been written to: /opensim_build
#8 7.564 Scanning dependencies of target osimLepton
#8 7.580 [  1%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/CompiledExpression.cpp.o
#8 7.580 [  1%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/ExpressionTreeNode.cpp.o
#8 7.580 [  1%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/Operation.cpp.o
#8 7.581 [  1%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/ParsedExpression.cpp.o
#8 7.592 [  1%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/Parser.cpp.o
#8 7.593 [  1%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/ExpressionProgram.cpp.o
#8 7.867 Scanning dependencies of target tropter
#8 7.924 [  1%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/utilities.cpp.o
#8 8.312 Scanning dependencies of target osimCommon
#8 8.544 [  1%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/APDMDataReader.cpp.o
#8 8.959 [  1%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/Exception.cpp.o
#8 8.978 [  2%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/About.cpp.o
#8 9.414 [  2%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/AbstractDataTable.cpp.o
#8 9.644 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/SparsityPattern.cpp.o
#8 9.700 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/AbstractProblem.cpp.o
#8 9.831 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/Problem.cpp.o
#8 9.853 [  3%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/AbstractProperty.cpp.o
#8 9.933 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/ProblemDecorator_double.cpp.o
#8 11.16 [  3%] Linking CXX shared library ../../libosimLepton.so
#8 11.53 [  3%] Built target osimLepton
#8 11.57 [  3%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/C3DFileAdapter.cpp.o
#8 11.92 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/ProblemDecorator_adouble.cpp.o
#8 13.40 [  3%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/CSVFileAdapter.cpp.o
#8 13.86 [  4%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/Solver.cpp.o
#8 14.19 [  4%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/SNOPTSolver.cpp.o
#8 16.15 [  5%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/CommonUtilities.cpp.o
#8 19.09 [  5%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/Component.cpp.o
#8 20.10 [  5%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/ComponentList.cpp.o
#8 109.2 OpenSim/Common/CMakeFiles/osimCommon.dir/build.make:62: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/APDMDataReader.cpp.o' failed
#8 109.2 c++: internal compiler error: Killed (program cc1plus)
#8 109.2 Please submit a full bug report,
#8 109.2 with preprocessed source if appropriate.
#8 109.2 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 109.2 make[2]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/APDMDataReader.cpp.o] Error 4
#8 109.2 make[2]: *** Waiting for unfinished jobs....
#8 109.2 [  5%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/IPOPTSolver.cpp.o
#8 110.1 [  5%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/internal/GraphColoring.cpp.o
#8 116.8 [  5%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/DirectCollocation.cpp.o
#8 161.8 c++: internal compiler error: Killed (program cc1plus)
#8 161.8 Please submit a full bug report,
#8 161.8 with preprocessed source if appropriate.
#8 161.8 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 161.8 OpenSim/Common/CMakeFiles/osimCommon.dir/build.make:182: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/CSVFileAdapter.cpp.o' failed
#8 161.8 make[2]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/CSVFileAdapter.cpp.o] Error 4
#8 161.9 [  6%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/Problem.cpp.o
#8 177.8 c++: internal compiler error: Killed (program cc1plus)
#8 177.8 Please submit a full bug report,
#8 177.8 with preprocessed source if appropriate.
#8 177.8 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 177.8 make[2]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/C3DFileAdapter.cpp.o] Error 4
#8 177.8 OpenSim/Common/CMakeFiles/osimCommon.dir/build.make:158: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/C3DFileAdapter.cpp.o' failed
#8 177.9 [  6%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/Iterate.cpp.o
#8 195.4 c++: internal compiler error: Killed (program cc1plus)
#8 195.4 Please submit a full bug report,
#8 195.4 with preprocessed source if appropriate.
#8 195.4 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 195.4 make[2]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/CommonUtilities.cpp.o] Error 4
#8 195.4 OpenSim/Common/CMakeFiles/osimCommon.dir/build.make:206: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/CommonUtilities.cpp.o' failed
#8 195.5 [  6%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/transcription/Trapezoidal.cpp.o
#8 195.8 [  6%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/transcription/HermiteSimpson.cpp.o
#8 233.3 c++: internal compiler error: Killed (program cc1plus)
#8 233.3 Please submit a full bug report,
#8 233.3 with preprocessed source if appropriate.
#8 233.3 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 233.3 OpenSim/Common/CMakeFiles/osimCommon.dir/build.make:230: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/Component.cpp.o' failed
#8 233.3 make[2]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/Component.cpp.o] Error 4
#8 233.3 make[1]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/all] Error 2
#8 233.3 make[1]: *** Waiting for unfinished jobs....
#8 233.3 CMakeFiles/Makefile2:511: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/all' failed
#8 242.0 [  7%] Linking CXX shared library ../../../libtropter.so
#8 242.9 [  7%] Built target tropter
#8 242.9 make: *** [all] Error 2
#8 242.9 Makefile:140: recipe for target 'all' failed
------
executor failed running [/bin/sh -c mkdir opensim_build && cd opensim_build && cmake ../opensim-core       -DSWIG_DIR=~/swig/share/swig -DSWIG_EXECUTABLE=~/swig/bin/swig -DBUILD_PYTHON_WRAPPING=ON       -DCMAKE_INSTALL_PREFIX="~/opensim_install" -DOPENSIM_DEPENDENCIES_DIR="~/opensim_dependencies_install"       -DOPENSIM_C3D_PARSER=ezc3d -DBUILD_TESTING=OFF       && make -j8 && make -j8 install && rm -rf ../opensim_build]: exit code: 2
The terminal process "zsh '-c', 'docker build --pull --rm -f "Dockerfile" -t osimdocker:latest "."'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by pwesberg** [comment]
On Win10, there also is an error using this [Dockerfile ](https://github.com/opensim-org/opensim-containers/blob/master/opensim-core/opensim-python/dockerfile-ubuntu)

```
> Executing task: docker build --pull --rm -f "Dockerfile" -t osimdocker:latest "." <


[+] Building 13.6s (4/9)
 => [internal] load build definition from Dockerfile                                                                                                                                    0.6s                                                                                                                                                                                        0.6s                                                  0.6s                                                                                                                                  0.5s
 => => transferring dockerfile: 1.36kB                                                                                                                                                  0.5s                                                                   3.0                                                                                                                  4.6s                                                  0.6s             o                                                                                                                    0.0s
 => [internal] load .dockerignore                                  b7426a1cba1cf366eb1795b4a5d857c94afc6378faa22ee582fae47c5                                                            8.2s                                                                   b7426a1cba1cf366eb1795b4a5d857c94afc6378faa22ee582fae47c5                                                            0.0s                                                  0.5s             e9827f40358 29.36MB / 261.41MB                                                                                       8.2s
 => => transferring context: 2B                                    89cc04292c9 7.34MB / 52.29MB                                                                                         8.2s                                                                   b089058cda7 13.63MB / 662.39MB                                                                                       8.2s                                                  0.5s             e582fae47c5 1.17kB / 1.17kB                                                                                          0.0s
 => [internal] load metadata for docker.io/aymanhab/opensim-deps:4.60c93c4cf88 2.00kB / 2.00kB                                                                                          0.0s3.0                                                                                                                  4.6s
 => [auth] aymanhab/opensim-deps:pull token for registry-1.docker.io                                                                                                                    0.0s
 => [1/5] FROM docker.io/aymanhab/opensim-deps:4.3.0@sha256:8928164b7426a1cba1cf366eb1795b4a5d857c94afc6378faa22ee582fae47c5                                                            8.4s
 => => resolve docker.io/aymanhab/opensim-deps:4.3.0@sha256:8928164b7426a1cba1cf366eb1795b4a5d857c94afc6378faa22ee582fae47c5                                                            0.0s
 => => sha256:78cf0b539ace12f3ac41b521d052919a277025365430e7d4d5744e9827f40358 29.36MB / 261.41MB                                      => [internal] load build definition from Dockerfile

                                                  0.6s
 => => transferring dockerfile: 1.36kB

                                                  0.6s
 => [internal] load .dockerignore

                                                  0.5s
 => => transferring context: 2B

                                                  0.5s
 => [internal] load metadata for docker.io/aymanhab/opensim-deps:4.3.0
                                                  4.6s
 => [auth] aymanhab/opensim-deps:pull token for registry-1.docker.io
                                                  0.0s
 => [1/5] FROM docker.io/aymanhab/opensim-deps:4.3.0@sha256:8928164b7426a1cba1cf366eb1795b4a5d857c94afc6378faa22ee582fae47c5
[+] Building 1397.3s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                    0.6s
 => => transferring dockerfile: 1.36kB                                                                                                                                                  0.6s
 => [internal] load .dockerignore                                                                                                                                                       0.5s
 => => transferring context: 2B                                                                                                                                                         0.5s
 => [internal] load metadata for docker.io/aymanhab/opensim-deps:4.3.0                                                                                                                  4.6s
 => [auth] aymanhab/opensim-deps:pull token for registry-1.docker.io                                                                                                                    0.0s
 => [1/5] FROM docker.io/aymanhab/opensim-deps:4.3.0@sha256:8928164b7426a1cba1cf366eb1795b4a5d857c94afc6378faa22ee582fae47c5                                                          166.5s
 => => resolve docker.io/aymanhab/opensim-deps:4.3.0@sha256:8928164b7426a1cba1cf366eb1795b4a5d857c94afc6378faa22ee582fae47c5                                                            0.0s
 => => sha256:78cf0b539ace12f3ac41b521d052919a277025365430e7d4d5744e9827f40358 261.41MB / 261.41MB                                                                                     68.6s
 => => sha256:db85243a27ddaa87ac7b931d9c0d23db42fbab38ecf09918a45fb89cc04292c9 52.29MB / 52.29MB                                                                                       38.1s
 => => sha256:6e0cc9488ab824cd86d90cb8e3b3ab9833db3b4523a57dfd37032b089058cda7 662.39MB / 662.39MB                                                                                    158.2s
 => => sha256:8928164b7426a1cba1cf366eb1795b4a5d857c94afc6378faa22ee582fae47c5 1.17kB / 1.17kB                                                                                          0.0s
 => => sha256:fc20170e348badff52ab2103c3d002ae4c17e6df1d1a08debca3160c93c4cf88 2.00kB / 2.00kB                                                                                          0.0s
 => => extracting sha256:78cf0b539ace12f3ac41b521d052919a277025365430e7d4d5744e9827f40358                                                                                               9.8s
 => => extracting sha256:db85243a27ddaa87ac7b931d9c0d23db42fbab38ecf09918a45fb89cc04292c9                                                                                               2.5s
 => => extracting sha256:6e0cc9488ab824cd86d90cb8e3b3ab9833db3b4523a57dfd37032b089058cda7                                                                                               7.9s
 => [2/5] RUN ln -snf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && echo America/Los_Angeles > /etc/timezone                                                                0.6s
 => [3/5] RUN apt-get update && DEBIAN_FRONTEND=noninteractive && apt-get --yes install         python3 python3-dev python3-numpy python3-scipy         python3-matplotlib python3-o  157.3s
 => [4/5] RUN mkdir ~/swig-source && cd ~/swig-source         && wget https://github.com/swig/swig/archive/refs/tags/rel-4.0.2.tar.gz         && tar xzf rel-4.0.2.tar.gz && cd swig-  42.4s
 => ERROR [5/5] RUN mkdir opensim_build && cd opensim_build && cmake ../opensim-core       -DSWIG_DIR=~/swig/share/swig -DSWIG_EXECUTABLE=~/swig/bin/swig -DBUILD_PYTHON_WRAPPING=O  1025.2s
------
 > [5/5] RUN mkdir opensim_build && cd opensim_build && cmake ../opensim-core       -DSWIG_DIR=~/swig/share/swig -DSWIG_EXECUTABLE=~/swig/bin/swig -DBUILD_PYTHON_WRAPPING=ON       -DCMAKE_INSTALL_PREFIX="~/opensim_install" -DOPENSIM_DEPENDENCIES_DIR="~/opensim_dependencies_install"       -DOPENSIM_C3D_PARSER=ezc3d -DBUILD_TESTING=OFF       && make -j8 && make -j8 install && rm -rf ../opensim_build:
#8 0.345 -- The C compiler identification is GNU 7.5.0
#8 0.403 -- The CXX compiler identification is GNU 7.5.0
#8 0.416 -- Check for working C compiler: /usr/bin/cc
#8 0.484 -- Check for working C compiler: /usr/bin/cc -- works
#8 0.489 -- Detecting C compiler ABI info
#8 0.548 -- Detecting C compiler ABI info - done
#8 0.557 -- Detecting C compile features
#8 0.742 -- Detecting C compile features - done
#8 0.747 -- Check for working CXX compiler: /usr/bin/c++
#8 0.818 -- Check for working CXX compiler: /usr/bin/c++ -- works
#8 0.819 -- Detecting CXX compiler ABI info
#8 0.890 -- Detecting CXX compiler ABI info - done
#8 0.899 -- Detecting CXX compile features
#8 1.211 -- Detecting CXX compile features - done
#8 1.212 -- NOTICE: Make sure all OpenSim dependencies are built with the same CMAKE_BUILD_TYPE (Linux) or CONFIGURATION (Xcode/MSVC) as OpenSim to avoid mysterious runtime errors.
#8 1.228 -- Found Git: /usr/bin/git (found version "2.17.1")
#8 1.232 fatal: not a git repository (or any of the parent directories): .git
#8 1.233 fatal: not a git repository (or any of the parent directories): .git
#8 1.265 -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3")
#8 1.458 -- Found NumPy: /usr/lib/python3/dist-packages/numpy/core/include (found version "1.13.3")
#8 1.465 -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3")
#8 1.466 -- Attempting to use dependencies from /root/opensim_dependencies_install
#8 1.471 -- Looking for pthread.h
#8 1.533 -- Looking for pthread.h - found
#8 1.533 -- Looking for pthread_create
#8 1.597 -- Looking for pthread_create - not found
#8 1.597 -- Looking for pthread_create in pthreads
#8 1.650 -- Looking for pthread_create in pthreads - not found
#8 1.650 -- Looking for pthread_create in pthread
#8 1.713 -- Looking for pthread_create in pthread - found
#8 1.714 -- Found Threads: TRUE
#8 1.733 -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
#8 1.736 -- Found ADOLC: /root/opensim_dependencies_install/adol-c/include
#8 1.736 -- Checking for module 'ipopt'
#8 1.747 --   Found ipopt, version 3.12.8
#8 1.777 -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
#8 1.900 -- Found SWIG: /root/swig/bin/swig (found suitable version "4.0.2", minimum required is "4.0.0")
#8 1.902 -- Discovering dependencies for SWIG module simbody (Python).
#8 2.186 -- Discovering dependencies for SWIG module common (Python).
#8 2.708 -- Discovering dependencies for SWIG module simulation (Python).
#8 3.340 -- Discovering dependencies for SWIG module actuators (Python).
#8 3.939 -- Discovering dependencies for SWIG module analyses (Python).
#8 4.551 -- Discovering dependencies for SWIG module tools (Python).
#8 5.191 -- Discovering dependencies for SWIG module examplecomponents (Python).
#8 5.794 -- Discovering dependencies for SWIG module moco (Python).
#8 6.484 -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
#8 6.488 -- Could NOT find LATEX (missing: LATEX_COMPILER PDFLATEX)
#8 6.493 -- The following features have been enabled:
#8 6.493
#8 6.493  * WITH_CASADI, Build CasADi support for Moco (OPENSIM_WITH_CASADI)
#8 6.493  * WITH_TROPTER, Build the tropter optimal control library (OPENSIM_WITH_TROPTER)
#8 6.493
#8 6.493 -- The following OPTIONAL packages have been found:
#8 6.493
#8 6.493  * Git
#8 6.493  * Simbody (required version >= 3.7)
#8 6.493  * docopt (required version >= 0.6.1)
#8 6.493
#8 6.493 -- The following REQUIRED packages have been found:
#8 6.493
#8 6.493  * PythonInterp (required version >= 3)
#8 6.493  * NumPy
#8 6.493  * PythonLibs (required version >= 3)
#8 6.493  * ezc3d
#8 6.493  * Threads
#8 6.493  * spdlog
#8 6.493  * casadi (required version >= 3.4.4), <https://web.casadi.org>
#8 6.493    Differentiation and optimizer interface.
#8 6.493  * Eigen3 (required version >= 3.3.1), <https://eigen.tuxfamily.org>
#8 6.493    Matrix library
#8 6.493  * PkgConfig
#8 6.493  * ColPack (required version >= 1.0.10), <https://github.com/CSCsw/ColPack>
#8 6.493    Exploiting sparsity structure of Jacobian
#8 6.493  * ADOLC, <https://projects.coin-or.org/ADOL-C>
#8 6.493    Computing derivatives for optimization
#8 6.493  * SWIG (required version >= 4.0.0)
#8 6.493
#8 6.493 -- The following features have been disabled:
#8 6.493
#8 6.493  * OpenMP, Parallelize derivative calculations (TROPTER_WITH_OPENMP)
#8 6.493  * WITH_SNOPT, Support the SNOPT optimization library (TROPTER_WITH_SNOPT)
#8 6.493
#8 6.493 -- The following OPTIONAL packages have not been found:
#8 6.493
#8 6.493  * Doxygen, <http://www.doxygen.org>
#8 6.493    Generate C++ API documentation
#8 6.493  * LATEX
#8 6.493
#8 6.505 -- Configuring done
#8 6.732 -- Generating done
#8 6.744 -- Build files have been written to: /opensim_build
#8 6.800 Scanning dependencies of target osimLepton
#8 6.810 [  0%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/ExpressionTreeNode.cpp.o
#8 6.810 [  0%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/ExpressionProgram.cpp.o
#8 6.811 [  0%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/CompiledExpression.cpp.o
#8 6.813 [  0%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/ParsedExpression.cpp.o
#8 6.820 [  1%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/Operation.cpp.o
#8 6.835 [  1%] Building CXX object Vendors/lepton/CMakeFiles/osimLepton.dir/src/Parser.cpp.o
#8 6.971 Scanning dependencies of target tropter
#8 7.034 [  1%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/utilities.cpp.o
#8 7.282 Scanning dependencies of target osimCommon
#8 7.447 [  1%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/APDMDataReader.cpp.o
#8 7.832 [  1%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/Exception.cpp.o
#8 7.938 [  2%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/About.cpp.o
#8 8.333 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/SparsityPattern.cpp.o
#8 8.517 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/AbstractProblem.cpp.o
#8 8.616 [  3%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/AbstractDataTable.cpp.o
#8 8.658 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/Problem.cpp.o
#8 8.743 [  3%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/AbstractProperty.cpp.o
#8 8.891 [  3%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/C3DFileAdapter.cpp.o
#8 9.671 [  3%] Linking CXX shared library ../../libosimLepton.so
#8 10.05 [  3%] Built target osimLepton
#8 10.07 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/ProblemDecorator_double.cpp.o
#8 10.25 [  3%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/CSVFileAdapter.cpp.o
#8 11.90 [  3%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/ProblemDecorator_adouble.cpp.o
#8 11.91 [  4%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/Solver.cpp.o
#8 12.35 [  4%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/SNOPTSolver.cpp.o
#8 12.50 [  4%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/IPOPTSolver.cpp.o
#8 15.22 [  5%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/CommonUtilities.cpp.o
#8 15.45 [  5%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/Component.cpp.o
#8 16.11 [  5%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/ComponentList.cpp.o
#8 35.52 [  5%] Building CXX object OpenSim/Common/CMakeFiles/osimCommon.dir/ComponentOutput.cpp.o
#8 213.1 OpenSim/Common/CMakeFiles/osimCommon.dir/build.make:158: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/C3DFileAdapter.cpp.o' failed
#8 213.1 c++: internal compiler error: Killed (program cc1plus)
#8 213.1 Please submit a full bug report,
#8 213.1 with preprocessed source if appropriate.
#8 213.1 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 213.1 make[2]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/C3DFileAdapter.cpp.o] Error 4
#8 213.1 make[2]: *** Waiting for unfinished jobs....
#8 213.4 [  5%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimization/internal/GraphColoring.cpp.o
#8 218.5 [  5%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/DirectCollocation.cpp.o
#8 302.7 c++: internal compiler error: Killed (program cc1plus)
#8 302.7 Please submit a full bug report,
#8 302.7 with preprocessed source if appropriate.
#8 302.7 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 302.7 make[2]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/APDMDataReader.cpp.o] Error 4
#8 302.7 OpenSim/Common/CMakeFiles/osimCommon.dir/build.make:62: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/APDMDataReader.cpp.o' failed
#8 303.0 [  6%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/Problem.cpp.o
#8 311.6 [  6%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/Iterate.cpp.o
#8 561.4 OpenSim/Common/CMakeFiles/osimCommon.dir/build.make:206: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/CommonUtilities.cpp.o' failed
#8 561.4 c++: internal compiler error: Killed (program cc1plus)
#8 561.4 Please submit a full bug report,
#8 561.4 with preprocessed source if appropriate.
#8 561.4 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 561.4 make[2]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/CommonUtilities.cpp.o] Error 4
#8 561.8 [  6%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/transcription/Trapezoidal.cpp.o
#8 591.9 [  6%] Building CXX object Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/transcription/HermiteSimpson.cpp.o
#8 719.9 Vendors/tropter/tropter/CMakeFiles/tropter.dir/build.make:398: recipe for target 'Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/transcription/Trapezoidal.cpp.o' failed
#8 719.9 c++: internal compiler error: Killed (program cc1plus)
#8 719.9 Please submit a full bug report,
#8 719.9 with preprocessed source if appropriate.
#8 719.9 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 719.9 make[2]: *** [Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/transcription/Trapezoidal.cpp.o] Error 4
#8 719.9 make[2]: *** Waiting for unfinished jobs....
#8 985.3 c++: internal compiler error: Killed (program cc1plus)
#8 985.3 Please submit a full bug report,
#8 985.3 with preprocessed source if appropriate.
#8 985.3 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#8 985.3 Vendors/tropter/tropter/CMakeFiles/tropter.dir/build.make:422: recipe for target 'Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/transcription/HermiteSimpson.cpp.o'
failed
#8 985.3 make[2]: *** [Vendors/tropter/tropter/CMakeFiles/tropter.dir/optimalcontrol/transcription/HermiteSimpson.cpp.o] Error 4
#8 1005.9 make[1]: *** [Vendors/tropter/tropter/CMakeFiles/tropter.dir/all] Error 2
#8 1005.9 CMakeFiles/Makefile2:277: recipe for target 'Vendors/tropter/tropter/CMakeFiles/tropter.dir/all' failed
#8 1005.9 make[1]: *** Waiting for unfinished jobs....
#8 1025.0 CMakeFiles/Makefile2:511: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/all' failed
#8 1025.0 make[1]: *** [OpenSim/Common/CMakeFiles/osimCommon.dir/all] Error 2
#8 1025.0 Makefile:140: recipe for target 'all' failed
#8 1025.0 make: *** [all] Error 2
------
executor failed running [/bin/sh -c mkdir opensim_build && cd opensim_build && cmake ../opensim-core       -DSWIG_DIR=~/swig/share/swig -DSWIG_EXECUTABLE=~/swig/bin/swig -DBUILD_PYTHON_WRAPPING=ON       -DCMAKE_INSTALL_PREFIX="~/opensim_install" -DOPENSIM_DEPENDENCIES_DIR="~/opensim_dependencies_install"       -DOPENSIM_C3D_PARSER=ezc3d -DBUILD_TESTING=OFF       && make -j8 && make -j8 install && rm -rf ../opensim_build]: exit code: 2
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker build --pull --rm -f "Dockerfile" -t osimdocker:latest "."" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by aymanhab** [comment]
One more thing, there's a PR to migrate to using stanfordnmbl/opensim-deps image, so you may use it from the PR here https://github.com/opensim-org/opensim-containers/pull/2 until merged.

**Comment by aymanhab** [comment]
@pwesberg I tried this on osx (still ubuntu 18.04 base image) and it worked exactly as expected. Are you trying to use an osx based image? I'm not sure what's the use case, can you help explain? Thank you

**Comment by aymanhab** [comment]
Closing as likely fixed by earlier updates, please open otherwise.

**Comment by pwesberg** [comment]
Dear Ayman, 

thanks for your answer. Unfortunately it is still not working for me. I think I need more understanding of docker, as it is not clear to me, how I need to use the ubuntu 18.04 base image to create my own opensim-python docker with your script. My hope was, with your script, I can easily build my own docker: just add my necessary python packages into you script and go for it. But it seems to be not easy plug&play and I need more information about how to work with docker image and Ill come back here later.
